---
title: "MLA2 CIA 3"
author: "Nikitha Reddy"
date: "2023-01-24"
output: html_document
---

```{r}
if (!require(tibble)) install.packages("tibble")
library(tibble)
if (!require(tidyverse)) install.packages("tidyverse")
library(tidyverse)
if (!require(lubridate)) install.packages("lubridate")
library(lubridate)
if (!require(viridis)) install.packages("viridis")
library(viridis)
if (!require(ggthemes)) install.packages("ggthemes")
library(ggthemes)
if (!require(gridExtra)) install.packages("gridExtra")
library(gridExtra)
if (!require(ggridges)) install.packages("ggridges")
library(ggridges)
if (!require(arules)) install.packages("arules")
library(arules)
if (!require(arulesViz)) install.packages("arulesViz")
library(arulesViz)
if (!require(datasets)) install.packages("datasets")
library(datasets)
```

```{r}
getwd()
```

```{r}
pos <- read.csv("rengas_pos.csv") %>% mutate(Date=as.Date(Date, format = "%d-%m-%Y"))

```

```{r}
str(pos)
```


```{r}
summary(pos)

```
```{r}
pos$Item<-as.factor(pos$Item)


```

```{r}
#viewing top 20 items
t20 <- pos %>% 
  group_by(Item) %>% 
  summarise(Count = n()) %>% 
  arrange(desc(Count)) %>%
  slice(1:15) %>% # keep the top 10 items
  ggplot(aes(x=reorder(Item,Count),y=Count,fill=Item))+
  geom_bar(stat="identity")+
  coord_flip()+
  ggtitle("Most popular line items")+
  theme(legend.position="none")
t20
```

```{r}
# Total items sold each weekday
x1 <- pos %>% 
  mutate(Day = wday(Date,label=T)) %>% 
  group_by(Day) %>% 
  summarise(Count= n()) %>% 
  ggplot(aes(x=Day,y=Count,fill=Day))+
  theme_fivethirtyeight()+
  geom_bar(stat="identity")+
  ggtitle("Total line items sold per weekday")+
  theme(legend.position="none")
x1
```

```{r}
# Top 50 transactions days per weekday
x2 <- pos %>% 
  group_by(Date) %>% 
  summarise(Count= n()) %>% 
  arrange(desc(Count)) %>% 
  slice(1:50) %>% 
  mutate(wday = wday(Date,label=T)) %>% 
  ggplot(aes(x=wday,y=Count,fill=wday))+
  theme_fivethirtyeight()+
  geom_bar(stat="identity")+
  ggtitle("Top 50 sales days by weekday")+
  theme(legend.position="none")
x2
```

```{r}
# Number of unique transactions per weekday
x5.1 <- pos %>% 
  mutate(Day = wday(Date,label=T)) %>% 
  group_by(Day) %>% 
  summarise(Count= n()) 

x5.2 <- pos %>% 
  mutate(wday=wday(Date,label=T)) %>% 
  group_by(wday,Billnum) %>% 
  summarise(n_distinct(Billnum)) %>% 
  summarise(Count=n())

  x5.3 <- data.frame(x5.1, # Days, total items
                   x5.2[2], # unique transactions
                   x5.1[2]/x5.2[2])  # items per unique transaction
colnames(x5.3) <- c("Day","Line","Unique","Items.Trans")

ggplot(x5.3,aes(x=Day,y=Items.Trans,fill=Day))+
  theme_fivethirtyeight()+
  geom_bar(stat="identity")+
  ggtitle("Total unique transactions per weekday")+
  theme(legend.position="none")+
  geom_text(aes(label=round(Items.Trans,1)), vjust=2)
```


```{r}
#Market Basket Analysis

y <- read.transactions("Rengas_pos.csv",
                       format="single",
                       cols=c(1,3),
                       sep=","
                       )
```

```{r}
itemFrequencyPlot(y,topN=5,type="relative")
itemFrequencyPlot(y,topN=5,type="absolute")
```

```{r}
trans<-y
trans
```
```{r}
summary(itemFrequency(trans))
x<-48168/length(trans)
x
```


```{r}
# Summary
summary(trans)
```
```{r}
# Glimpse
glimpse(trans)
```

```{r}
# Structure
str(trans)
```
```{r}
# Absolute Item Frequency Plot
itemFrequencyPlot(trans, topN=15, type="absolute", col="wheat2",xlab="Item name", 
                  ylab="Frequency (absolute)", main="Absolute Item Frequency Plot")
```
```{r}
# Relative Item Frequency Plot
itemFrequencyPlot(trans, topN=15, type="relative", col="lightcyan2", xlab="Item name", 
                  ylab="Frequency (relative)", main="Relative Item Frequency Plot")
```




```{r}
trans<-y
# Support and confidence values
supportLevels <- c(0.1, 0.05, 0.01, 0.005)
confidenceLevels <- c(0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1)

# Empty integers 
rules_sup10 <- integer(length=9)
rules_sup5 <- integer(length=9)
rules_sup1 <- integer(length=9)
rules_sup0.5 <- integer(length=9)

# Apriori algorithm with a support level of 10%
for (i in 1:length(confidenceLevels)) {
  
  rules_sup10[i] <- length(apriori(trans, parameter=list(sup=supportLevels[1], 
                                   conf=confidenceLevels[i], target="rules")))
  
}

# Apriori algorithm with a support level of 5%
for (i in 1:length(confidenceLevels)){
  
  rules_sup5[i] <- length(apriori(trans, parameter=list(sup=supportLevels[2], 
                                  conf=confidenceLevels[i], target="rules")))
  
}
# Apriori algorithm with a support level of 1%
for (i in 1:length(confidenceLevels)){
  
  rules_sup1[i] <- length(apriori(trans, parameter=list(sup=supportLevels[3], 
                                  conf=confidenceLevels[i], target="rules")))
  
}

# Apriori algorithm with a support level of 0.5%
for (i in 1:length(confidenceLevels)){
  
  rules_sup0.5[i] <- length(apriori(trans, parameter=list(sup=supportLevels[4], 
                                    conf=confidenceLevels[i], target="rules")))
  
}
```

```{r}
# Number of rules found with a support level of 10%
plot1 <- qplot(confidenceLevels, rules_sup10, geom=c("point", "line"), 
               xlab="Confidence level", ylab="Number of rules found", 
               main="Apriori with a support level of 10%") +
  #scale_y_continuous(breaks=seq(0,250,30)) +
  theme_bw()

# Number of rules found with a support level of 5%
plot2 <- qplot(confidenceLevels, rules_sup5, geom=c("point", "line"), 
               xlab="Confidence level", ylab="Number of rules found", 
               main="Apriori with a support level of 5%") + 
  #scale_y_continuous(breaks=seq(0,50, 2)) +
  theme_bw()

# Number of rules found with a support level of 1%
plot3 <- qplot(confidenceLevels, rules_sup1, geom=c("point", "line"), 
               xlab="Confidence level", ylab="Number of rules found", 
               main="Apriori with a support level of 1%") + 
  scale_y_continuous(breaks=seq(0, 250, 30)) +
  theme_bw()

# Number of rules found with a support level of 0.5%
plot4 <- qplot(confidenceLevels, rules_sup0.5, geom=c("point", "line"), 
               xlab="Confidence level", ylab="Number of rules found", 
               main="Apriori with a support level of 0.5%") + 
  scale_y_continuous(breaks=seq(0, 1250, 100)) +
  theme_bw()

# Subplot
grid.arrange(plot1, plot2, plot3, plot4, ncol=2)
```

```{r}
# Data frame
num_rules <- data.frame(rules_sup10, rules_sup5, rules_sup1, rules_sup0.5, confidenceLevels)

# Number of rules found with a support level of 10%, 5%, 1% and 0.5%
ggplot(data=num_rules, aes(x=confidenceLevels)) +
  
  # Plot line and points (support level of 10%)
  geom_line(aes(y=rules_sup10, colour="Support level of 10%")) + 
  geom_point(aes(y=rules_sup10, colour="Support level of 10%")) +
  
  # Plot line and points (support level of 5%)
  geom_line(aes(y=rules_sup5, colour="Support level of 5%")) +
  geom_point(aes(y=rules_sup5, colour="Support level of 5%")) +
  
  # Plot line and points (support level of 1%)
  geom_line(aes(y=rules_sup1, colour="Support level of 1%")) + 
  geom_point(aes(y=rules_sup1, colour="Support level of 1%")) +
  
  # Plot line and points (support level of 0.5%)
  geom_line(aes(y=rules_sup0.5, colour="Support level of 0.5%")) +
  geom_point(aes(y=rules_sup0.5, colour="Support level of 0.5%")) +
  
  # Labs and theme
  labs(x="Confidence levels", y="Number of rules found", 
       title="Apriori algorithm with different support levels") +
  theme_bw() +
  theme(legend.title=element_blank())
```

```{r}
 #Apriori algorithm execution with a support level of 1% and a confidence level of 50%
rules_sup1_conf50 <- apriori(trans, parameter=list(sup=supportLevels[3], 
                             conf=confidenceLevels[5], target="rules"))
```

```{r}
# Inspect association rules
inspect(rules_sup1_conf50)
```
```{r}
# Scatter plot
plot(rules_sup1_conf50, measure=c("support", "lift"), shading="confidence")
```
```{r}
#Graph (default layout)
plot(rules_sup1_conf50, method="graph")
```


```{r}
# Grouped matrix plot
plot(rules_sup1_conf50, method="grouped")
```
```{r}
# Parallel coordinates plot
plot(rules_sup1_conf50, method="paracoord", control=list(reorder=TRUE))
```


```{r}
# Apriori algorithm execution with a support level of 0.5% and a confidence level of 10%
rules_sup0.5_conf10 <- apriori(trans, parameter=list(sup=supportLevels[4], conf=confidenceLevels[9], target="rules"))
```

```{r}
# Scatter plot
plot(rules_sup0.5_conf10, measure=c("support", "lift"), shading="confidence", jitter=0)
```


```{r}
#Assign rules
#0.0006228201
rules <- apriori(y,parameter=list(support=0.01,confidence=.5))
rules
```

```{r}
#rules=apriori(y,parameter=list(supp=0.001,conf=0.8))
#inspect(rules[1:50])
sort_rules=sort(rules,by="support", decreasing=TRUE)
inspect(sort_rules)
```

```{r}
sort_rules=sort(rules,by="lift", decreasing=TRUE)
inspect(sort_rules)
```
```{r}

sort_rules=sort(rules,by="confidence", decreasing=TRUE)
inspect(sort_rules)
```

```{r}
redundant<-is.redundant(rules, measure="confidence")
which(redundant)
rules.pruned<-rules[!redundant]
rules.pruned<-sort(rules.pruned,by="lift")
inspect(rules.pruned)
```


# THANK YOU!








